# Generated by Django 5.2.13 on 2026-06-16 23:07

import django.contrib.auth.models
import django.contrib.auth.validators
import django.db.models.deletion
import django.utils.timezone
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Medidor',
            fields=[
                ('id_medidor', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('numero_medidor', models.CharField(blank=True, max_length=50, null=True, unique=True)),
                ('manzano', models.CharField(blank=True, max_length=50, null=True)),
                ('parcela', models.CharField(blank=True, max_length=50, null=True)),
                ('estado', models.CharField(choices=[('Activo', 'Activo'), ('Cortado', 'Cortado'), ('Dado de baja', 'Dado de baja')], default='Activo', max_length=20)),
            ],
            options={
                'db_table': 'medidores',
                'ordering': ['numero_medidor'],
            },
        ),
        migrations.CreateModel(
            name='Tarifa',
            fields=[
                ('id_tarifa', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50)),
                ('costo_por_cubo', models.DecimalField(decimal_places=2, max_digits=10)),
                ('cuota_fija', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('multa_atraso', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, verbose_name='Multa por atraso')),
                ('dias_gracia', models.PositiveIntegerField(default=0, verbose_name='Días de gracia para pago')),
                ('fecha_vigencia', models.DateField(auto_now_add=True, null=True)),
                ('activa', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'tarifas',
                'ordering': ['-id_tarifa'],
            },
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('rol', models.CharField(choices=[('admin', 'Administrador'), ('tesorero', 'Tesorero'), ('lector', 'Lector de medidores'), ('socio', 'Socio')], default='socio', max_length=20)),
                ('ci', models.CharField(blank=True, max_length=20, null=True, unique=True, verbose_name='Carnet de identidad')),
                ('telefono', models.CharField(blank=True, max_length=20, null=True)),
                ('activo', models.BooleanField(default=True)),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'Usuario',
                'verbose_name_plural': 'Usuarios',
                'db_table': 'usuarios',
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Lectura',
            fields=[
                ('id_lectura', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('periodo', models.CharField(max_length=20)),
                ('fecha_lectura', models.DateTimeField(auto_now_add=True)),
                ('lectura_anterior', models.DecimalField(decimal_places=2, max_digits=10)),
                ('lectura_actual', models.DecimalField(decimal_places=2, max_digits=10)),
                ('consumo_cubos', models.DecimalField(decimal_places=2, default=Decimal('0.00'), editable=False, max_digits=10)),
                ('foto_evidencia', models.ImageField(blank=True, null=True, upload_to='lecturas/fotos/', verbose_name='Foto del medidor')),
                ('observacion', models.TextField(blank=True, null=True, verbose_name='Observación de lectura')),
                ('creado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lecturas_registradas', to=settings.AUTH_USER_MODEL)),
                ('medidor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lecturas', to='agua.medidor')),
            ],
            options={
                'db_table': 'lecturas',
                'ordering': ['-fecha_lectura'],
            },
        ),
        migrations.CreateModel(
            name='Cobro',
            fields=[
                ('id_recibo', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('numero_recibo', models.PositiveIntegerField(blank=True, editable=False, null=True, unique=True)),
                ('fecha_emision', models.DateField(auto_now_add=True)),
                ('importe_consumo', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('recargo_falta_pago', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('instalacion_clandestina', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('multa_alteracion', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('reconexion', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('limpieza_tanque', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('falta_asamblea', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('otros', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('monto_total', models.DecimalField(decimal_places=2, default=Decimal('0.00'), editable=False, max_digits=10)),
                ('estado_pago', models.CharField(choices=[('Pendiente', 'Pendiente'), ('En Revision', 'En Revision'), ('Cancelado', 'Cancelado'), ('Vencido', 'Vencido')], default='Pendiente', max_length=20)),
                ('lectura', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='recibo', to='agua.lectura')),
            ],
            options={
                'db_table': 'recibos',
                'ordering': ['-fecha_emision', '-numero_recibo'],
            },
        ),
        migrations.CreateModel(
            name='Pago',
            fields=[
                ('id_pago', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('fecha_pago', models.DateTimeField(auto_now_add=True)),
                ('monto_pagado', models.DecimalField(decimal_places=2, max_digits=10)),
                ('metodo_pago', models.CharField(choices=[('efectivo', 'Efectivo'), ('transferencia', 'Transferencia'), ('qr', 'QR')], default='efectivo', max_length=20)),
                ('foto_comprobante', models.ImageField(blank=True, null=True, upload_to='pagos/comprobantes/', verbose_name='Foto del comprobante')),
                ('recibo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pagos', to='agua.cobro')),
                ('registrado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pagos_registrados', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'pagos',
                'ordering': ['-fecha_pago'],
            },
        ),
        migrations.CreateModel(
            name='Socio',
            fields=[
                ('id_socio', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('ci', models.CharField(max_length=20, unique=True, verbose_name='Carnet de identidad')),
                ('codigo_cliente', models.CharField(blank=True, max_length=50, null=True, unique=True, verbose_name='Código de cliente')),
                ('nombre_completo', models.CharField(max_length=150, verbose_name='Nombre completo')),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
                ('usuario', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='socio_perfil', to=settings.AUTH_USER_MODEL, verbose_name='Usuario de acceso móvil')),
            ],
            options={
                'verbose_name': 'Socio',
                'verbose_name_plural': 'Socios',
                'db_table': 'socios',
                'ordering': ['nombre_completo'],
            },
        ),
        migrations.AddField(
            model_name='medidor',
            name='co_titulares',
            field=models.ManyToManyField(blank=True, related_name='medidores_cotitular', to='agua.socio', verbose_name='Co-titulares'),
        ),
        migrations.AddField(
            model_name='medidor',
            name='socio',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='medidores_titular', to='agua.socio'),
        ),
        migrations.AddField(
            model_name='cobro',
            name='socio',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recibos', to='agua.socio'),
        ),
        migrations.CreateModel(
            name='TransaccionQRBNB',
            fields=[
                ('id_transaccion', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('qr_id_bnb', models.CharField(blank=True, max_length=100, null=True)),
                ('monto', models.DecimalField(decimal_places=2, max_digits=10)),
                ('qr_base64', models.TextField(blank=True, null=True)),
                ('estado', models.CharField(choices=[('GENERADO', 'Generado'), ('PAGADO', 'Pagado'), ('EXPIRADO', 'Expirado'), ('ERROR', 'Error'), ('CANCELADO', 'Cancelado')], default='GENERADO', max_length=20)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_pago', models.DateTimeField(blank=True, null=True)),
                ('observacion', models.TextField(blank=True, null=True)),
                ('recibo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transacciones_qr', to='agua.cobro')),
            ],
            options={
                'db_table': 'transacciones_qr_bnb',
                'ordering': ['-fecha_creacion'],
            },
        ),
        migrations.AddConstraint(
            model_name='lectura',
            constraint=models.UniqueConstraint(fields=('medidor', 'periodo'), name='unique_lectura_por_periodo'),
        ),
    ]