# Generated by Django 5.2.13 on 2026-06-17 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agua', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='socio',
            name='estado',
            field=models.CharField(default='ACTIVO', max_length=20, verbose_name='Estado'),
        ),
        migrations.AddField(
            model_name='socio',
            name='fecha_retiro',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha de retiro'),
        ),
        migrations.AddField(
            model_name='socio',
            name='observacion_retiro',
            field=models.TextField(blank=True, null=True, verbose_name='Observación de retiro'),
        ),
        migrations.AddField(
            model_name='socio',
            name='telefono',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Teléfono'),
        ),
    ]
