# Generated by Django 5.2.13 on 2026-07-01 02:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agua', '0002_socio_estado_socio_fecha_retiro_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='QRGenerico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('monto', models.DecimalField(decimal_places=2, max_digits=10, unique=True, verbose_name='Monto exacto (Bs)')),
                ('imagen_qr', models.ImageField(upload_to='qrs_genericos/', verbose_name='Imagen del QR')),
                ('activo', models.BooleanField(default=True, help_text='Desmarcar si este QR ya no se debe usar')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'QR Genérico',
                'verbose_name_plural': 'QRs Genéricos',
                'ordering': ['monto'],
            },
        ),
    ]
