# Generated by Django 5.2.13 on 2026-07-28 17:25

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agua', '0003_qrgenerico'),
    ]

    operations = [
        migrations.AddField(
            model_name='tarifa',
            name='costo_falta_asamblea',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, verbose_name='Multa por falta a asamblea'),
        ),
        migrations.AddField(
            model_name='tarifa',
            name='costo_instalacion_clandestina',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, verbose_name='Multa por instalación clandestina'),
        ),
        migrations.AddField(
            model_name='tarifa',
            name='costo_limpieza_tanque',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, verbose_name='Costo de limpieza de tanque'),
        ),
        migrations.AddField(
            model_name='tarifa',
            name='costo_multa_alteracion',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, verbose_name='Multa por alteración de medidor'),
        ),
        migrations.AddField(
            model_name='tarifa',
            name='costo_reconexion',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, verbose_name='Costo de reconexión'),
        ),
    ]
