# Generated by Django 5.2.13 on 2026-08-10 21:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agua', '0004_tarifa_costo_falta_asamblea_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='qrgenerico',
            name='monto',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Déjalo vacío para crear el QR genérico SIN monto fijo (el socio ve cuánto debe y paga esa cantidad manualmente).', max_digits=10, null=True, unique=True, verbose_name='Monto exacto (Bs)'),
        ),
    ]
