# Generated by Django 5.2.13 on 2026-08-18 22:27

import django.db.models.deletion
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agua', '0005_alter_qrgenerico_monto'),
    ]

    operations = [
        migrations.AddField(
            model_name='tarifa',
            name='costo_afiliacion',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, verbose_name='Costo de afiliación (acción de agua)'),
        ),
        migrations.CreateModel(
            name='Afiliacion',
            fields=[
                ('id_afiliacion', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('tipo', models.CharField(choices=[('NUEVO', 'Socio nuevo'), ('TRANSFERENCIA', 'Transferencia de medidor')], default='NUEVO', max_length=20, verbose_name='Tipo de afiliación')),
                ('monto', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Monto de la afiliación')),
                ('fecha_pago', models.DateField(verbose_name='Fecha de pago de la acción')),
                ('observacion', models.TextField(blank=True, null=True, verbose_name='Observación')),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
                ('medidor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='afiliaciones', to='agua.medidor', verbose_name='Medidor asociado (si es transferencia)')),
                ('registrado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='afiliaciones_registradas', to=settings.AUTH_USER_MODEL, verbose_name='Registrado por')),
                ('socio', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='afiliacion', to='agua.socio', verbose_name='Socio')),
            ],
            options={
                'verbose_name': 'Afiliación',
                'verbose_name_plural': 'Afiliaciones',
                'db_table': 'afiliaciones',
                'ordering': ['-fecha_pago'],
            },
        ),
    ]
