# Generated by Django 5.2.13 on 2026-09-04 19:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agua', '0006_tarifa_costo_afiliacion_afiliacion'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bitacora',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('usuario_nombre', models.CharField(blank=True, help_text='Copia del nombre del usuario, por si su cuenta se elimina después.', max_length=150)),
                ('accion', models.CharField(choices=[('CREAR', 'Creación'), ('EDITAR', 'Edición'), ('ELIMINAR', 'Eliminación'), ('EXPORTAR', 'Exportación / Backup'), ('IMPORTAR', 'Importación / Restauración')], max_length=15)),
                ('modelo', models.CharField(max_length=100, verbose_name='Módulo/Modelo afectado')),
                ('objeto_id', models.CharField(blank=True, max_length=50, null=True)),
                ('objeto_repr', models.CharField(blank=True, max_length=255, verbose_name='Descripción del registro afectado')),
                ('detalles', models.TextField(blank=True, help_text='Información adicional, si aplica.')),
                ('ip', models.GenericIPAddressField(blank=True, null=True)),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='acciones_bitacora', to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
            options={
                'verbose_name': 'Registro de Bitácora',
                'verbose_name_plural': 'Bitácora',
                'ordering': ['-fecha'],
            },
        ),
    ]
