# Generated by Django 5.2.13 on 2026-10-03 22:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def cobros_parciales_a_pendiente(apps, schema_editor):
    """
    Antes "En Revision" significaba "cobro con pago parcial". Ahora significa
    "comprobante esperando revisión". Los cobros que ya estaban así (ninguno
    tiene todavía un pago por revisar) vuelven a Pendiente; pasan solos a
    Vencido cuando corresponda.
    """
    Cobro = apps.get_model('agua', 'Cobro')
    Cobro.objects.filter(estado_pago='En Revision').update(estado_pago='Pendiente')


class Migration(migrations.Migration):

    dependencies = [
        ('agua', '0007_bitacora'),
    ]

    operations = [
        migrations.AddField(
            model_name='pago',
            name='estado',
            field=models.CharField(choices=[('En Revision', 'En Revision'), ('Aprobado', 'Aprobado'), ('Rechazado', 'Rechazado')], default='Aprobado', max_length=20),
        ),
        migrations.AddField(
            model_name='pago',
            name='fecha_revision',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pago',
            name='motivo_rechazo',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='pago',
            name='nro_transaccion',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='pago',
            name='revisado_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pagos_revisados', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='pago',
            name='metodo_pago',
            field=models.CharField(choices=[('efectivo', 'Efectivo'), ('qr', 'QR')], default='efectivo', max_length=20),
        ),
        migrations.RunPython(cobros_parciales_a_pendiente, migrations.RunPython.noop),
    ]
